### ISSUE TITLE
Design the XML Structure

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#15]
Ideally to be done after the ER diagram as you'll need to know the database composition.

This isn't the hardest task just document it somewhere.

**Comment by LousyLeonard** [comment]
Setting to Josh to do but you'll need to wait for Tommy to finish the ER diagram.

**Comment by ghost** [comment]
ER diagram completed, see:
https://github.com/LousyLeonard/YeovilHealthCareProducts/files/720284/Database.ER.Diagram.docx

Over to you Josh!

**Comment by JoshYoungman** [comment]
Here's the XML structure based off of the ER diagram. GitHub doesn't support .xml files so I uploaded it as a .txt file: 

[Database.txt](https://github.com/LousyLeonard/YeovilHealthCareProducts/files/724445/Database.txt)
