### ISSUE TITLE
Configure Git in Eclipse

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#22]
Something pretty like this please.

![image](https://cloud.githubusercontent.com/assets/22559496/22124027/fd7dda3a-de85-11e6-86a5-c85faf82ca4b.png)

Open the eGit perspective and just paste in the URL to this github. There's a bit more to it though, so let me know if there's any problems.

**Comment by LousyLeonard** [comment]
Done on the 20/01/2017.

Closing...

**Comment by ghost** [comment]
Set to closed
