### ISSUE TITLE
Provide evidence of agile methodology controlling the Iteration 

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#23]
Don't really know how to show this, going to be the biggest bother of the coursework.

I think this GitHub project/issues set up I'm doing will go some way towards it but it's not technically agile... but then the iterations part is agile....

![image](https://cloud.githubusercontent.com/assets/22559496/22124306/2fd16780-de87-11e6-8f8a-3c2bbf48f3c0.png)

**Comment by ghost** [comment]
I can start looking more at some of the documentation-related tasks as this is quite important

**Comment by ghost** [comment]
Done. Closing 08/03/2017.
