### ISSUE TITLE
Plan Iteration 2

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#25]
Big broad issue to cover the planning of Iteration 2.

Really we should be looking for the same level of detail as iteration 1 planning.

Deliverable
Quality Criteria
Gantt Chart

**Comment by ghost** [comment]
I already have a brief template of the quality criteria for Iteration 2 so we can use this if necessary

**Comment by ghost** [comment]
Created template and started putting together the document.

See: 
https://docs.google.com/document/d/14Q0oCp5hEy7hodg2P74Vz5xNNzuuAsfdBco_OvbZTfI/edit?ts=58ad9428#

**Comment by ghost** [comment]
Added quality criteria to the document.

Josh completed first drafts of deliverable section.

**Comment by ghost** [comment]
Done and added to iteration one and two document. 

Closing 08/03/2017.
