### ISSUE TITLE
Implement the database

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#27]
Write the database creation SQL. 

I'm thinking it might eventually be good to move this into a java class to but lets do one thing at a time.

Don't forget to use the ER Diagram Tommy created for us in /design.

**Comment by ghost** [comment]
I can volunteer to do this if you want seeing as I love databases so much ;)

**Comment by ghost** [comment]
Created a SQL database creation script that can be used to implement the database

See: 
YeovilHealthCareProducts/Iteration 1 Documentation/design/Database Creation Script.sql

Setting to closed 25/01/2017
