### ISSUE TITLE
Identify the SQL queries we will need

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#29]
What data is the website going to need from the database. Try to cover as many possibilities as possible.

I.e 
1) All the products. (For displaying on the initial visit or no search criteria)
2) All the different brands for populating the brand search at the side.
3) Searchs for keywords. (Including name and brand)

**Comment by ghost** [comment]
Initial ideas:
- Select all products

- Select all products by brand

- Select all products by keyword

**Comment by ghost** [comment]
Added "Select all brands" to the above list, and then implemented SQL query scripts into Java classes

Setting to closed 27/01/2017
