### ISSUE TITLE
Write the SQL Queries we will need

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#31]
Gonna have to wait until they've been identified.

but we're gonna need them written in SQL to eventually be called by java classes.

**Comment by ghost** [comment]
Created three SQL queries, but they need checking and verifying to ensure that the joins are correct.

See: 
YeovilHealthCareProducts/Iteration 1 Documentation/design/SQL Product Query.sql

Leaving open until verified for closure.

**Comment by ghost** [comment]
Agreed and verified. SQL queries written and implemented into Java classes.

Setting to closed 27/01/2017
