### ISSUE TITLE
Incorporate the SQL into Java classes

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#32]
Develop a series of classes that will call the defined SQL queries and return the appropriate results. They should take in parameters where parameters are needed.

This should be done after the SQL has been written.

This should also include the SQL to create the databases so that we can do that in a java format as well.

**Comment by ghost** [comment]
Table creation scripts and select queries implemented into Java classes.

I believe these to function correctly, however, we need a good test to ensure this.

Setting to closed 27/01/2017
