### ISSUE TITLE
Implement SQL INSERT scripts into Java Classes

### ISSUE THREAD

**Issue by ghost** [LousyLeonard/YeovilHealthCareProducts#37]
As above

**Comment by ghost** [comment]
I have created a initial draft of the Java classes.

We will need to verify as a team that it does as we want it to. For example, I have used MAX(ID) to capture the foreign key values, but this works on the assumption that the data is created at the same time (just after) the associated product or brand. I think this should be okay for our purposes though, but I'm happy to reconsider it if not.

**Comment by LousyLeonard** [comment]
Me and Tommy worked through this together on the 01/02/2017.

**Comment by ghost** [comment]
Finished and completed basic testing .

Setting to closed 01/02/2017
