### ISSUE TITLE
Install MySQL server 

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#4]
Recommend the community edition if you don't want to pay.

Running it through the installer and installing it as a service recommended.

Bonus point for installing it without the installer.

**Comment by ghost** [comment]
Collaborated on installing the developmental environment on 18/01/2016. 

MySQL Community server was installed. The same MySQL version was installed on each team member's computer. Some members installed the compressed file format without the use of the installer, whilst others installed MySQL by using the executable file. Either method resulted in the same end installation and so this is satisfactory to the requirement.

Closing on 20/01/2017.
