### ISSUE TITLE
Display prices to two decimal places

### ISSUE THREAD

**Issue by JoshYoungman** [LousyLeonard/YeovilHealthCareProducts#51]
Display all product prices to two decimal places. Currently, when a product price ends in 0, it is only displayed to one decimal place.

![image](https://cloud.githubusercontent.com/assets/22937097/22594727/28404bbc-ea1c-11e6-80bd-18005227960d.png)

**Comment by LousyLeonard** [comment]
Worked through this together in class on the 03/02/2017.
