### ISSUE TITLE
(Recommended) Install MySQL Workbench

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#7]
Look at it handle my DB like a boss

![image](https://cloud.githubusercontent.com/assets/22559496/22122901/79a2fd0c-de81-11e6-8d45-0f5a6d235744.png)

**Comment by LousyLeonard** [comment]
Haven't figured out how to get it to display value as opposed to tables yet..

**Comment by LousyLeonard** [comment]
Tommy wants to use command line MySQL.

I will be using the workbench, I installed it during a group activity at Josh's on the 18/01/2017.

**Comment by LousyLeonard** [comment]
Josh installed it during a group activity on the 20/01/2017.

**Comment by ghost** [comment]
I also installed the MySQL Workbench to maintain the consistency of our development environments
