### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by LousyLeonard** [LousyLeonard/YeovilHealthCareProducts#9]
ER diagram please.

Taking into account:
The option to search through the current product range to be provided as three options:
By keyword search
By brand name
By generic product name

So without thinking I see; ID, Name, Keyword(s), brand as fields here....

**Comment by LousyLeonard** [comment]
during a discussion at college tommy agreed to take on this work.

**Comment by ghost** [comment]
This database should, therefore, have entities for brand, product, and keyword, with an association table between keyword and product. Images will also be required in the products so it may be necessary to have an entity for image as well.

**Comment by ghost** [comment]
Database design decided, and entity-relationship diagrams created.

I've discovered that storing the product images in the database itself is a bad idea. I suggest instead that we reference the file paths for the images in the database that will be used to source the images externally. 

Setting to closed on 20/01/2017.

[Database ER Diagram.docx](https://github.com/LousyLeonard/YeovilHealthCareProducts/files/720284/Database.ER.Diagram.docx)

**Comment by LousyLeonard** [comment]
Hey Tommy I committed this diagram into the git stream for you.

**Comment by ghost** [comment]
Cheers! :)
